// debug_log.h
#ifndef LOCAL_LOG_CONFIG_H
#define LOCAL_LOG_CONFIG_H
#pragma once
// #include "debug_log.h"

#define LOG_LEVEL_ERROR_PRINT LOG_LEVEL_TRACE
#define LOG_LEVEL_MAIN LOG_LEVEL_TRACE
#define LOG_LEVEL_ADC_BTN LOG_LEVEL_INFO // Включено для отладки кнопок
#define LOG_LEVEL_CONTROL LOG_LEVEL_WARN
#define LOG_LEVEL_PID LOG_LEVEL_NONE
#define LOG_LEVEL_HADWARE LOG_LEVEL_TRACE
#define LOG_LEVEL_MENU LOG_LEVEL_TRACE
#define LOG_LEVEL_SOFT_PWM LOG_LEVEL_NONE
#define LOG_LEVEL_THERMISTOR LOG_LEVEL_NONE
#define LOG_LEVEL_ERRORBUS LOG_LEVEL_NONE
#define LOG_LEVEL_SCALE LOG_LEVEL_WARN
#define LOG_LEVEL_UART LOG_LEVEL_WARN

#endif
