// Auto-generated. Do not edit.
#include <string.h>
#include <EEPROM.h>
#include "menu_state.h"
#include "menu_types.h"
#include "menu_eeprom.h"
#include "menu_eeprom_io.h"

MenuState menu;

void MenuState::initDefaults(){
  this->number_controller = (uint8_t)0;
  for (int i=0;i<NUM_UNITS;i++) this->dry_temp[i] = 60.0f;
  for (int i=0;i<NUM_UNITS;i++) this->dry_time[i] = (uint16_t)240;
  for (int i=0;i<NUM_UNITS;i++) this->storage_temp[i] = (uint8_t)45;
  for (int i=0;i<NUM_UNITS;i++) this->storage_hum[i] = (uint8_t)12;
  for (int i=0;i<NUM_UNITS;i++) this->storage_hum_priority[i] = true;
  for (int i=0;i<NUM_UNITS;i++) this->start_stage_by_number[i] = (uint8_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_01_temp[i] = (uint8_t)50;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_01_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_01_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_02_temp[i] = (uint8_t)60;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_02_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_02_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_03_temp[i] = (uint8_t)70;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_03_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_03_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_04_temp[i] = (uint8_t)60;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_04_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_04_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_05_temp[i] = (uint8_t)50;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_05_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_05_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_06_temp[i] = (uint8_t)70;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_06_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_06_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_07_temp[i] = (uint8_t)90;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_07_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_07_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_08_temp[i] = (uint8_t)75;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_08_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_08_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_09_temp[i] = (uint8_t)65;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_09_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_09_time[i] = (uint16_t)1;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_10_temp[i] = (uint8_t)55;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_10_ramps_time[i] = (uint16_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->profile_stage_10_time[i] = (uint16_t)1;
  this->preset_pla_temp = 45.0f;
  this->preset_pla_time = (uint16_t)240;
  this->preset_pla_cf_temp = 45.0f;
  this->preset_pla_cf_time = (uint16_t)240;
  this->preset_pla_gf_temp = 45.0f;
  this->preset_pla_gf_time = (uint16_t)240;
  this->preset_petg_temp = 60.0f;
  this->preset_petg_time = (uint16_t)180;
  this->preset_petg_cf_temp = 65.0f;
  this->preset_petg_cf_time = (uint16_t)180;
  this->preset_petg_gf_temp = 60.0f;
  this->preset_petg_gf_time = (uint16_t)180;
  this->preset_abs_temp = 80.0f;
  this->preset_abs_time = (uint16_t)240;
  this->preset_abs_cf_temp = 90.0f;
  this->preset_abs_cf_time = (uint16_t)240;
  this->preset_abs_gf_temp = 90.0f;
  this->preset_abs_gf_time = (uint16_t)240;
  this->preset_pa_temp = 90.0f;
  this->preset_pa_time = (uint16_t)240;
  this->preset_pa_cf_temp = 100.0f;
  this->preset_pa_cf_time = (uint16_t)240;
  this->preset_pa_gf_temp = 100.0f;
  this->preset_pa_gf_time = (uint16_t)240;
  this->preset_pc_temp = 100.0f;
  this->preset_pc_time = (uint16_t)360;
  this->preset_pc_cf_temp = 100.0f;
  this->preset_pc_cf_time = (uint16_t)360;
  this->preset_my1_temp = 70.0f;
  this->preset_my1_time = (uint16_t)360;
  this->preset_my2_temp = 80.0f;
  this->preset_my2_time = (uint16_t)360;
  this->preset_my3_temp = 90.0f;
  this->preset_my3_time = (uint16_t)360;
  this->scales_count = (uint8_t)0;
  this->tare_spool1 = 0.0f;
  this->tare_spool2 = 0.0f;
  this->tare_spool3 = 0.0f;
  this->tare_spool4 = 0.0f;
  for (int i=0;i<NUM_UNITS;i++) this->storage_auto[i] = true;
  for (int i=0;i<NUM_UNITS;i++) this->storage_auto_dry[i] = true;
  for (int i=0;i<NUM_UNITS;i++) this->storage_rh_hyst[i] = (uint8_t)5;
  for (int i=0;i<NUM_UNITS;i++) this->storage_dry_temp_mode[i] = false;
  for (int i=0;i<NUM_UNITS;i++) this->storage_dry_temp_by_dry_temp[i] = (uint8_t)90;
  for (int i=0;i<NUM_UNITS;i++) this->storage_min_hold_sec[i] = (uint16_t)30;
  for (int i=0;i<NUM_UNITS;i++) this->pid_kp_heater[i] = 9.81f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_ki_heater[i] = 0.084f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_kd_heater[i] = 87.825f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_gain_heater[i] = 9.81f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_kp_chamber[i] = 5.873f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_ki_chamber[i] = 0.18f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_kd_chamber[i] = 50.402f;
  for (int i=0;i<NUM_UNITS;i++) this->pid_gain_chamber[i] = 5.873f;
  for (int i=0;i<NUM_UNITS;i++) this->heater_max_temp[i] = 130.0f;
  for (int i=0;i<NUM_UNITS;i++) this->air_max_temp[i] = 90.0f;
  for (int i=0;i<NUM_UNITS;i++) this->delta_c[i] = (uint8_t)40;
  for (int i=0;i<NUM_UNITS;i++) this->heater_delta_is_percent[i] = false;
  for (int i=0;i<NUM_UNITS;i++) this->vh_max_err[i] = 250.0f;
  for (int i=0;i<NUM_UNITS;i++) this->vh_heating_gain[i] = 0.3f;
  for (int i=0;i<NUM_UNITS;i++) this->vh_check_gain_time_s[i] = (uint16_t)60;
  for (int i=0;i<NUM_UNITS;i++) this->vh_arm_pwm_min_pct[i] = (uint8_t)70;
  for (int i=0;i<NUM_UNITS;i++) this->fan_temp_on_c[i] = 55.0f;
  for (int i=0;i<NUM_UNITS;i++) this->fan_hyst_c[i] = 5.0f;
  for (int i=0;i<NUM_UNITS;i++) this->servo_closed_angle[i] = (uint8_t)20;
  for (int i=0;i<NUM_UNITS;i++) this->servo_open_angle[i] = (uint8_t)50;
  for (int i=0;i<NUM_UNITS;i++) this->servo_time_closed[i] = (uint16_t)600;
  for (int i=0;i<NUM_UNITS;i++) this->servo_time_open[i] = (uint16_t)30;
  for (int i=0;i<NUM_UNITS;i++) this->servo_smart_mode[i] = false;
  this->ign_ext_cmd = false;
  this->drying_session_count = (uint16_t)0;
  this->storage_session_count = (uint16_t)0;
  this->profile_session_count = (uint16_t)0;
  this->port1_mode = (uint8_t)2;
  this->port2_mode = (uint8_t)3;
  this->port3_mode = (uint8_t)1;
  this->ws_enabled = false;
  this->units_count = (uint8_t)1;
  this->language = (uint8_t)1;
}

void MenuState::loadFromEEPROM(){
  uint32_t magic=0, ver=0;
  ee_read(EE_SYS_OFF_MAGIC, magic);
  ee_read(EE_SYS_OFF_VERSION, ver);
  if (magic != EE_MAGIC || ver != EE_VERSION) return;
  ee_read(2220, this->number_controller);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_DRY_TEMP(i), this->dry_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_DRY_TIME(i), this->dry_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_TEMP(i), this->storage_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_HUM(i), this->storage_hum[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_HUM_PRIORITY(i), this->storage_hum_priority[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_START_STAGE_BY_NUMBER(i), this->start_stage_by_number[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_01_TEMP(i), this->profile_stage_01_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_01_RAMPS(i), this->profile_stage_01_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_01_HOLD(i), this->profile_stage_01_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_02_TEMP(i), this->profile_stage_02_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_02_RAMPS(i), this->profile_stage_02_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_02_HOLD(i), this->profile_stage_02_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_03_TEMP(i), this->profile_stage_03_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_03_RAMPS(i), this->profile_stage_03_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_03_HOLD(i), this->profile_stage_03_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_04_TEMP(i), this->profile_stage_04_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_04_RAMPS(i), this->profile_stage_04_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_04_HOLD(i), this->profile_stage_04_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_05_TEMP(i), this->profile_stage_05_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_05_RAMPS(i), this->profile_stage_05_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_05_HOLD(i), this->profile_stage_05_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_06_TEMP(i), this->profile_stage_06_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_06_RAMPS(i), this->profile_stage_06_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_06_HOLD(i), this->profile_stage_06_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_07_TEMP(i), this->profile_stage_07_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_07_RAMPS(i), this->profile_stage_07_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_07_HOLD(i), this->profile_stage_07_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_08_TEMP(i), this->profile_stage_08_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_08_RAMPS(i), this->profile_stage_08_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_08_HOLD(i), this->profile_stage_08_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_09_TEMP(i), this->profile_stage_09_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_09_RAMPS(i), this->profile_stage_09_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_09_HOLD(i), this->profile_stage_09_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_10_TEMP(i), this->profile_stage_10_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_10_RAMPS(i), this->profile_stage_10_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STAGE_10_HOLD(i), this->profile_stage_10_time[i]);
  ee_read(2401, this->preset_pla_temp);
  ee_read(2405, this->preset_pla_time);
  ee_read(2407, this->preset_pla_cf_temp);
  ee_read(2411, this->preset_pla_cf_time);
  ee_read(2413, this->preset_pla_gf_temp);
  ee_read(2417, this->preset_pla_gf_time);
  ee_read(2419, this->preset_petg_temp);
  ee_read(2423, this->preset_petg_time);
  ee_read(2425, this->preset_petg_cf_temp);
  ee_read(2429, this->preset_petg_cf_time);
  ee_read(2431, this->preset_petg_gf_temp);
  ee_read(2435, this->preset_petg_gf_time);
  ee_read(2437, this->preset_abs_temp);
  ee_read(2441, this->preset_abs_time);
  ee_read(2443, this->preset_abs_cf_temp);
  ee_read(2447, this->preset_abs_cf_time);
  ee_read(2449, this->preset_abs_gf_temp);
  ee_read(2453, this->preset_abs_gf_time);
  ee_read(2455, this->preset_pa_temp);
  ee_read(2459, this->preset_pa_time);
  ee_read(2461, this->preset_pa_cf_temp);
  ee_read(2465, this->preset_pa_cf_time);
  ee_read(2467, this->preset_pa_gf_temp);
  ee_read(2471, this->preset_pa_gf_time);
  ee_read(2473, this->preset_pc_temp);
  ee_read(2477, this->preset_pc_time);
  ee_read(2479, this->preset_pc_cf_temp);
  ee_read(2483, this->preset_pc_cf_time);
  ee_read(2485, this->preset_my1_temp);
  ee_read(2489, this->preset_my1_time);
  ee_read(2491, this->preset_my2_temp);
  ee_read(2495, this->preset_my2_time);
  ee_read(2497, this->preset_my3_temp);
  ee_read(2501, this->preset_my3_time);
  ee_read(2503, this->scales_count);
  ee_read(2504, this->tare_spool1);
  ee_read(2508, this->tare_spool2);
  ee_read(2512, this->tare_spool3);
  ee_read(2516, this->tare_spool4);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_AUTO(i), this->storage_auto[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_AUTO_DRY(i), this->storage_auto_dry[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_RH_HYST(i), this->storage_rh_hyst[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_DRY_TEMP_MODE(i), this->storage_dry_temp_mode[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP(i), this->storage_dry_temp_by_dry_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_STORAGE_MIN_HOLD_SEC(i), this->storage_min_hold_sec[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KP_HEATER(i), this->pid_kp_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KI_HEATER(i), this->pid_ki_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KD_HEATER(i), this->pid_kd_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_GAIN_HEATER(i), this->pid_gain_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KP_CHAMBER(i), this->pid_kp_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KI_CHAMBER(i), this->pid_ki_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_KD_CHAMBER(i), this->pid_kd_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_PID_GAIN_CHAMBER(i), this->pid_gain_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_HEATER_MAX_TEMP(i), this->heater_max_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_AIR_MAX_TEMP(i), this->air_max_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_DELTA(i), this->delta_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_HEATER_DELTA_IS_PERCENT(i), this->heater_delta_is_percent[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_VH_MAX_ERR(i), this->vh_max_err[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_VH_HEATING_GAIN(i), this->vh_heating_gain[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_VH_CHECK_GAIN_TIME(i), this->vh_check_gain_time_s[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_VH_ARM_PWM_MIN(i), this->vh_arm_pwm_min_pct[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_FAN_TEMP_ON(i), this->fan_temp_on_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_FAN_HYST(i), this->fan_hyst_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_SERVO_CLOSED_ANGLE(i), this->servo_closed_angle[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_SERVO_OPEN_ANGLE(i), this->servo_open_angle[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_SERVO_TIME_CLOSED(i), this->servo_time_closed[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_SERVO_TIME_OPEN(i), this->servo_time_open[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_read((uint16_t)EE_OFF_SERVO_SMART_MODE(i), this->servo_smart_mode[i]);
  ee_read(2745, this->ign_ext_cmd);
  ee_read(2746, this->drying_session_count);
  ee_read(2748, this->storage_session_count);
  ee_read(2750, this->profile_session_count);
  ee_read(2752, this->port1_mode);
  ee_read(2753, this->port2_mode);
  ee_read(2754, this->port3_mode);
  ee_read(2755, this->ws_enabled);
  ee_read(2756, this->units_count);
  ee_read(2757, this->language);
}

void MenuState::saveToEEPROM(){
  ee_write(EE_SYS_OFF_MAGIC,   (uint32_t)EE_MAGIC);
  ee_write(EE_SYS_OFF_VERSION, (uint32_t)EE_VERSION);
  ee_store_field(2220, this->number_controller);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_DRY_TEMP(i), this->dry_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_DRY_TIME(i), this->dry_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_TEMP(i), this->storage_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_HUM(i), this->storage_hum[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_HUM_PRIORITY(i), this->storage_hum_priority[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_START_STAGE_BY_NUMBER(i), this->start_stage_by_number[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_01_TEMP(i), this->profile_stage_01_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_01_RAMPS(i), this->profile_stage_01_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_01_HOLD(i), this->profile_stage_01_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_02_TEMP(i), this->profile_stage_02_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_02_RAMPS(i), this->profile_stage_02_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_02_HOLD(i), this->profile_stage_02_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_03_TEMP(i), this->profile_stage_03_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_03_RAMPS(i), this->profile_stage_03_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_03_HOLD(i), this->profile_stage_03_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_04_TEMP(i), this->profile_stage_04_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_04_RAMPS(i), this->profile_stage_04_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_04_HOLD(i), this->profile_stage_04_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_05_TEMP(i), this->profile_stage_05_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_05_RAMPS(i), this->profile_stage_05_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_05_HOLD(i), this->profile_stage_05_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_06_TEMP(i), this->profile_stage_06_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_06_RAMPS(i), this->profile_stage_06_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_06_HOLD(i), this->profile_stage_06_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_07_TEMP(i), this->profile_stage_07_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_07_RAMPS(i), this->profile_stage_07_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_07_HOLD(i), this->profile_stage_07_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_08_TEMP(i), this->profile_stage_08_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_08_RAMPS(i), this->profile_stage_08_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_08_HOLD(i), this->profile_stage_08_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_09_TEMP(i), this->profile_stage_09_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_09_RAMPS(i), this->profile_stage_09_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_09_HOLD(i), this->profile_stage_09_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_10_TEMP(i), this->profile_stage_10_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_10_RAMPS(i), this->profile_stage_10_ramps_time[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STAGE_10_HOLD(i), this->profile_stage_10_time[i]);
  ee_store_field(2401, this->preset_pla_temp);
  ee_store_field(2405, this->preset_pla_time);
  ee_store_field(2407, this->preset_pla_cf_temp);
  ee_store_field(2411, this->preset_pla_cf_time);
  ee_store_field(2413, this->preset_pla_gf_temp);
  ee_store_field(2417, this->preset_pla_gf_time);
  ee_store_field(2419, this->preset_petg_temp);
  ee_store_field(2423, this->preset_petg_time);
  ee_store_field(2425, this->preset_petg_cf_temp);
  ee_store_field(2429, this->preset_petg_cf_time);
  ee_store_field(2431, this->preset_petg_gf_temp);
  ee_store_field(2435, this->preset_petg_gf_time);
  ee_store_field(2437, this->preset_abs_temp);
  ee_store_field(2441, this->preset_abs_time);
  ee_store_field(2443, this->preset_abs_cf_temp);
  ee_store_field(2447, this->preset_abs_cf_time);
  ee_store_field(2449, this->preset_abs_gf_temp);
  ee_store_field(2453, this->preset_abs_gf_time);
  ee_store_field(2455, this->preset_pa_temp);
  ee_store_field(2459, this->preset_pa_time);
  ee_store_field(2461, this->preset_pa_cf_temp);
  ee_store_field(2465, this->preset_pa_cf_time);
  ee_store_field(2467, this->preset_pa_gf_temp);
  ee_store_field(2471, this->preset_pa_gf_time);
  ee_store_field(2473, this->preset_pc_temp);
  ee_store_field(2477, this->preset_pc_time);
  ee_store_field(2479, this->preset_pc_cf_temp);
  ee_store_field(2483, this->preset_pc_cf_time);
  ee_store_field(2485, this->preset_my1_temp);
  ee_store_field(2489, this->preset_my1_time);
  ee_store_field(2491, this->preset_my2_temp);
  ee_store_field(2495, this->preset_my2_time);
  ee_store_field(2497, this->preset_my3_temp);
  ee_store_field(2501, this->preset_my3_time);
  ee_store_field(2503, this->scales_count);
  ee_store_field(2504, this->tare_spool1);
  ee_store_field(2508, this->tare_spool2);
  ee_store_field(2512, this->tare_spool3);
  ee_store_field(2516, this->tare_spool4);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_AUTO(i), this->storage_auto[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_AUTO_DRY(i), this->storage_auto_dry[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_RH_HYST(i), this->storage_rh_hyst[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_DRY_TEMP_MODE(i), this->storage_dry_temp_mode[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP(i), this->storage_dry_temp_by_dry_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_STORAGE_MIN_HOLD_SEC(i), this->storage_min_hold_sec[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KP_HEATER(i), this->pid_kp_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KI_HEATER(i), this->pid_ki_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KD_HEATER(i), this->pid_kd_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_GAIN_HEATER(i), this->pid_gain_heater[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KP_CHAMBER(i), this->pid_kp_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KI_CHAMBER(i), this->pid_ki_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_KD_CHAMBER(i), this->pid_kd_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_PID_GAIN_CHAMBER(i), this->pid_gain_chamber[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_HEATER_MAX_TEMP(i), this->heater_max_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_AIR_MAX_TEMP(i), this->air_max_temp[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_DELTA(i), this->delta_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_HEATER_DELTA_IS_PERCENT(i), this->heater_delta_is_percent[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_VH_MAX_ERR(i), this->vh_max_err[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_VH_HEATING_GAIN(i), this->vh_heating_gain[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_VH_CHECK_GAIN_TIME(i), this->vh_check_gain_time_s[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_VH_ARM_PWM_MIN(i), this->vh_arm_pwm_min_pct[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_FAN_TEMP_ON(i), this->fan_temp_on_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_FAN_HYST(i), this->fan_hyst_c[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_SERVO_CLOSED_ANGLE(i), this->servo_closed_angle[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_SERVO_OPEN_ANGLE(i), this->servo_open_angle[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_SERVO_TIME_CLOSED(i), this->servo_time_closed[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_SERVO_TIME_OPEN(i), this->servo_time_open[i]);
  for (int i=0;i<NUM_UNITS;i++) ee_store_field((uint16_t)EE_OFF_SERVO_SMART_MODE(i), this->servo_smart_mode[i]);
  ee_store_field(2745, this->ign_ext_cmd);
  ee_store_field(2746, this->drying_session_count);
  ee_store_field(2748, this->storage_session_count);
  ee_store_field(2750, this->profile_session_count);
  ee_store_field(2752, this->port1_mode);
  ee_store_field(2753, this->port2_mode);
  ee_store_field(2754, this->port3_mode);
  ee_store_field(2755, this->ws_enabled);
  ee_store_field(2756, this->units_count);
  ee_store_field(2757, this->language);
}