// Auto-generated. Do not edit.
#pragma once
#include <stdint.h>

#define EE_MAGIC   0x4D4E5551
#define EE_VERSION 2

#ifndef NUM_UNITS
#define NUM_UNITS 3
#endif

// System area (fixed at start of EEPROM)
#define EE_SYS_OFF_MAGIC   0
#define EE_SYS_OFF_VERSION 4
#define EE_OFF_WT_HOURS    8
#define EE_OFF_WT_MINUTES  12

// ---- Scales calibration (protected, inside system area) ----
#define EE_SYS_CAL_BASE            16

// Ноль для каждой катушки: uint32_t[4]
#define EE_SYS_CAL_ZERO_BASE       (EE_SYS_CAL_BASE + 0)
#define EE_SYS_CAL_ZERO(i)         (EE_SYS_CAL_ZERO_BASE + (uint16_t)((i) * sizeof(uint32_t))) // i=0..3

// Оффсет/масштаб для каждой катушки: uint32_t[4]
#define EE_SYS_CAL_OFFSET_BASE     (EE_SYS_CAL_ZERO_BASE + 4*4)
#define EE_SYS_CAL_OFFSET(i)       (EE_SYS_CAL_OFFSET_BASE + (uint16_t)((i) * sizeof(uint32_t)))

// общий размер блока калибровки + 16 на всякий
#define EE_SYS_CAL_SIZE            (sizeof(uint32_t) * 4 * 2 + 16)

// ---- Scales temperature offsets table (uint32_t[4][6]) ----
#define EE_SCALE_TEMP_BASE              (EE_SYS_CAL_BASE + EE_SYS_CAL_SIZE)
#define EE_SCALE_TEMP_STRIDE_SPOOL      (6 * 4)   // 6 points per spool * 4 bytes each
// Accessor: spool i=0..3, point j=0..5 (e.g., temps 60..110)
#define EE_SCALE_TEMP(i,j)             (EE_SCALE_TEMP_BASE + (uint16_t)((i) * EE_SCALE_TEMP_STRIDE_SPOOL + (j) * sizeof(uint32_t)))
// Table size: 4 spools * 6 points * 4 bytes = 96 bytes
#define EE_SCALE_TEMP_SIZE             (4*6*4)

// Итоговый размер системной области: 16 (MAGIC..MINUTES) + 48 (калибровка) = 64
#define EE_SYS_AREA_SIZE           160

// ---- Error log area ----
#define ERRLOG_CAP           128
#define ERRLOG_REC_SIZE      16
#define ERRLOG_HDR_SIZE      12
#define EE_ERR_BASE          (EE_SYS_AREA_SIZE)
#define EE_ERR_OFF_HDR       (EE_ERR_BASE)
#define EE_ERR_OFF_RECS      (EE_ERR_BASE + ERRLOG_HDR_SIZE)
#define EE_ERR_AREA_SIZE     (ERRLOG_HDR_SIZE + (ERRLOG_CAP * ERRLOG_REC_SIZE))

#define EE_OFF_CONTROLLER_CHOICE 2220
#define EE_OFF_DRY_TEMP_BASE   2221
#define EE_OFF_DRY_TEMP_STRIDE 4
#define EE_OFF_DRY_TEMP(i) (EE_OFF_DRY_TEMP_BASE + (uint16_t)((i) * EE_OFF_DRY_TEMP_STRIDE))
#define EE_OFF_DRY_TIME_BASE   2233
#define EE_OFF_DRY_TIME_STRIDE 2
#define EE_OFF_DRY_TIME(i) (EE_OFF_DRY_TIME_BASE + (uint16_t)((i) * EE_OFF_DRY_TIME_STRIDE))
#define EE_OFF_STORAGE_TEMP_BASE   2239
#define EE_OFF_STORAGE_TEMP_STRIDE 1
#define EE_OFF_STORAGE_TEMP(i) (EE_OFF_STORAGE_TEMP_BASE + (uint16_t)((i) * EE_OFF_STORAGE_TEMP_STRIDE))
#define EE_OFF_STORAGE_HUM_BASE   2242
#define EE_OFF_STORAGE_HUM_STRIDE 1
#define EE_OFF_STORAGE_HUM(i) (EE_OFF_STORAGE_HUM_BASE + (uint16_t)((i) * EE_OFF_STORAGE_HUM_STRIDE))
#define EE_OFF_STORAGE_HUM_PRIORITY_BASE   2245
#define EE_OFF_STORAGE_HUM_PRIORITY_STRIDE 1
#define EE_OFF_STORAGE_HUM_PRIORITY(i) (EE_OFF_STORAGE_HUM_PRIORITY_BASE + (uint16_t)((i) * EE_OFF_STORAGE_HUM_PRIORITY_STRIDE))
#define EE_OFF_START_STAGE_BY_NUMBER_BASE   2248
#define EE_OFF_START_STAGE_BY_NUMBER_STRIDE 1
#define EE_OFF_START_STAGE_BY_NUMBER(i) (EE_OFF_START_STAGE_BY_NUMBER_BASE + (uint16_t)((i) * EE_OFF_START_STAGE_BY_NUMBER_STRIDE))
#define EE_OFF_STAGE_01_TEMP_BASE   2251
#define EE_OFF_STAGE_01_TEMP_STRIDE 1
#define EE_OFF_STAGE_01_TEMP(i) (EE_OFF_STAGE_01_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_01_TEMP_STRIDE))
#define EE_OFF_STAGE_01_RAMPS_BASE   2254
#define EE_OFF_STAGE_01_RAMPS_STRIDE 2
#define EE_OFF_STAGE_01_RAMPS(i) (EE_OFF_STAGE_01_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_01_RAMPS_STRIDE))
#define EE_OFF_STAGE_01_HOLD_BASE   2260
#define EE_OFF_STAGE_01_HOLD_STRIDE 2
#define EE_OFF_STAGE_01_HOLD(i) (EE_OFF_STAGE_01_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_01_HOLD_STRIDE))
#define EE_OFF_STAGE_02_TEMP_BASE   2266
#define EE_OFF_STAGE_02_TEMP_STRIDE 1
#define EE_OFF_STAGE_02_TEMP(i) (EE_OFF_STAGE_02_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_02_TEMP_STRIDE))
#define EE_OFF_STAGE_02_RAMPS_BASE   2269
#define EE_OFF_STAGE_02_RAMPS_STRIDE 2
#define EE_OFF_STAGE_02_RAMPS(i) (EE_OFF_STAGE_02_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_02_RAMPS_STRIDE))
#define EE_OFF_STAGE_02_HOLD_BASE   2275
#define EE_OFF_STAGE_02_HOLD_STRIDE 2
#define EE_OFF_STAGE_02_HOLD(i) (EE_OFF_STAGE_02_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_02_HOLD_STRIDE))
#define EE_OFF_STAGE_03_TEMP_BASE   2281
#define EE_OFF_STAGE_03_TEMP_STRIDE 1
#define EE_OFF_STAGE_03_TEMP(i) (EE_OFF_STAGE_03_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_03_TEMP_STRIDE))
#define EE_OFF_STAGE_03_RAMPS_BASE   2284
#define EE_OFF_STAGE_03_RAMPS_STRIDE 2
#define EE_OFF_STAGE_03_RAMPS(i) (EE_OFF_STAGE_03_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_03_RAMPS_STRIDE))
#define EE_OFF_STAGE_03_HOLD_BASE   2290
#define EE_OFF_STAGE_03_HOLD_STRIDE 2
#define EE_OFF_STAGE_03_HOLD(i) (EE_OFF_STAGE_03_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_03_HOLD_STRIDE))
#define EE_OFF_STAGE_04_TEMP_BASE   2296
#define EE_OFF_STAGE_04_TEMP_STRIDE 1
#define EE_OFF_STAGE_04_TEMP(i) (EE_OFF_STAGE_04_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_04_TEMP_STRIDE))
#define EE_OFF_STAGE_04_RAMPS_BASE   2299
#define EE_OFF_STAGE_04_RAMPS_STRIDE 2
#define EE_OFF_STAGE_04_RAMPS(i) (EE_OFF_STAGE_04_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_04_RAMPS_STRIDE))
#define EE_OFF_STAGE_04_HOLD_BASE   2305
#define EE_OFF_STAGE_04_HOLD_STRIDE 2
#define EE_OFF_STAGE_04_HOLD(i) (EE_OFF_STAGE_04_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_04_HOLD_STRIDE))
#define EE_OFF_STAGE_05_TEMP_BASE   2311
#define EE_OFF_STAGE_05_TEMP_STRIDE 1
#define EE_OFF_STAGE_05_TEMP(i) (EE_OFF_STAGE_05_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_05_TEMP_STRIDE))
#define EE_OFF_STAGE_05_RAMPS_BASE   2314
#define EE_OFF_STAGE_05_RAMPS_STRIDE 2
#define EE_OFF_STAGE_05_RAMPS(i) (EE_OFF_STAGE_05_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_05_RAMPS_STRIDE))
#define EE_OFF_STAGE_05_HOLD_BASE   2320
#define EE_OFF_STAGE_05_HOLD_STRIDE 2
#define EE_OFF_STAGE_05_HOLD(i) (EE_OFF_STAGE_05_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_05_HOLD_STRIDE))
#define EE_OFF_STAGE_06_TEMP_BASE   2326
#define EE_OFF_STAGE_06_TEMP_STRIDE 1
#define EE_OFF_STAGE_06_TEMP(i) (EE_OFF_STAGE_06_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_06_TEMP_STRIDE))
#define EE_OFF_STAGE_06_RAMPS_BASE   2329
#define EE_OFF_STAGE_06_RAMPS_STRIDE 2
#define EE_OFF_STAGE_06_RAMPS(i) (EE_OFF_STAGE_06_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_06_RAMPS_STRIDE))
#define EE_OFF_STAGE_06_HOLD_BASE   2335
#define EE_OFF_STAGE_06_HOLD_STRIDE 2
#define EE_OFF_STAGE_06_HOLD(i) (EE_OFF_STAGE_06_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_06_HOLD_STRIDE))
#define EE_OFF_STAGE_07_TEMP_BASE   2341
#define EE_OFF_STAGE_07_TEMP_STRIDE 1
#define EE_OFF_STAGE_07_TEMP(i) (EE_OFF_STAGE_07_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_07_TEMP_STRIDE))
#define EE_OFF_STAGE_07_RAMPS_BASE   2344
#define EE_OFF_STAGE_07_RAMPS_STRIDE 2
#define EE_OFF_STAGE_07_RAMPS(i) (EE_OFF_STAGE_07_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_07_RAMPS_STRIDE))
#define EE_OFF_STAGE_07_HOLD_BASE   2350
#define EE_OFF_STAGE_07_HOLD_STRIDE 2
#define EE_OFF_STAGE_07_HOLD(i) (EE_OFF_STAGE_07_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_07_HOLD_STRIDE))
#define EE_OFF_STAGE_08_TEMP_BASE   2356
#define EE_OFF_STAGE_08_TEMP_STRIDE 1
#define EE_OFF_STAGE_08_TEMP(i) (EE_OFF_STAGE_08_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_08_TEMP_STRIDE))
#define EE_OFF_STAGE_08_RAMPS_BASE   2359
#define EE_OFF_STAGE_08_RAMPS_STRIDE 2
#define EE_OFF_STAGE_08_RAMPS(i) (EE_OFF_STAGE_08_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_08_RAMPS_STRIDE))
#define EE_OFF_STAGE_08_HOLD_BASE   2365
#define EE_OFF_STAGE_08_HOLD_STRIDE 2
#define EE_OFF_STAGE_08_HOLD(i) (EE_OFF_STAGE_08_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_08_HOLD_STRIDE))
#define EE_OFF_STAGE_09_TEMP_BASE   2371
#define EE_OFF_STAGE_09_TEMP_STRIDE 1
#define EE_OFF_STAGE_09_TEMP(i) (EE_OFF_STAGE_09_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_09_TEMP_STRIDE))
#define EE_OFF_STAGE_09_RAMPS_BASE   2374
#define EE_OFF_STAGE_09_RAMPS_STRIDE 2
#define EE_OFF_STAGE_09_RAMPS(i) (EE_OFF_STAGE_09_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_09_RAMPS_STRIDE))
#define EE_OFF_STAGE_09_HOLD_BASE   2380
#define EE_OFF_STAGE_09_HOLD_STRIDE 2
#define EE_OFF_STAGE_09_HOLD(i) (EE_OFF_STAGE_09_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_09_HOLD_STRIDE))
#define EE_OFF_STAGE_10_TEMP_BASE   2386
#define EE_OFF_STAGE_10_TEMP_STRIDE 1
#define EE_OFF_STAGE_10_TEMP(i) (EE_OFF_STAGE_10_TEMP_BASE + (uint16_t)((i) * EE_OFF_STAGE_10_TEMP_STRIDE))
#define EE_OFF_STAGE_10_RAMPS_BASE   2389
#define EE_OFF_STAGE_10_RAMPS_STRIDE 2
#define EE_OFF_STAGE_10_RAMPS(i) (EE_OFF_STAGE_10_RAMPS_BASE + (uint16_t)((i) * EE_OFF_STAGE_10_RAMPS_STRIDE))
#define EE_OFF_STAGE_10_HOLD_BASE   2395
#define EE_OFF_STAGE_10_HOLD_STRIDE 2
#define EE_OFF_STAGE_10_HOLD(i) (EE_OFF_STAGE_10_HOLD_BASE + (uint16_t)((i) * EE_OFF_STAGE_10_HOLD_STRIDE))
#define EE_OFF_PRESET_PLA_TEMP 2401
#define EE_OFF_PRESET_PLA_TIME 2405
#define EE_OFF_PRESET_PLA_CF_TEMP 2407
#define EE_OFF_PRESET_PLA_CF_TIME 2411
#define EE_OFF_PRESET_PLA_GF_TEMP 2413
#define EE_OFF_PRESET_PLA_GF_TIME 2417
#define EE_OFF_PRESET_PETG_TEMP 2419
#define EE_OFF_PRESET_PETG_TIME 2423
#define EE_OFF_PRESET_PETG_CF_TEMP 2425
#define EE_OFF_PRESET_PETG_CF_TIME 2429
#define EE_OFF_PRESET_PETG_GF_TEMP 2431
#define EE_OFF_PRESET_PETG_GF_TIME 2435
#define EE_OFF_PRESET_ABS_TEMP 2437
#define EE_OFF_PRESET_ABS_TIME 2441
#define EE_OFF_PRESET_ABS_CF_TEMP 2443
#define EE_OFF_PRESET_ABS_CF_TIME 2447
#define EE_OFF_PRESET_ABS_GF_TEMP 2449
#define EE_OFF_PRESET_ABS_GF_TIME 2453
#define EE_OFF_PRESET_PA_TEMP 2455
#define EE_OFF_PRESET_PA_TIME 2459
#define EE_OFF_PRESET_PA_CF_TEMP 2461
#define EE_OFF_PRESET_PA_CF_TIME 2465
#define EE_OFF_PRESET_PA_GF_TEMP 2467
#define EE_OFF_PRESET_PA_GF_TIME 2471
#define EE_OFF_PRESET_PC_TEMP 2473
#define EE_OFF_PRESET_PC_TIME 2477
#define EE_OFF_PRESET_PC_CF_TEMP 2479
#define EE_OFF_PRESET_PC_CF_TIME 2483
#define EE_OFF_PRESET_MY1_TEMP 2485
#define EE_OFF_PRESET_MY1_TIME 2489
#define EE_OFF_PRESET_MY2_TEMP 2491
#define EE_OFF_PRESET_MY2_TIME 2495
#define EE_OFF_PRESET_MY3_TEMP 2497
#define EE_OFF_PRESET_MY3_TIME 2501
#define EE_OFF_SCALES_COUNT 2503
#define EE_OFF_TARE_SPOOL1 2504
#define EE_OFF_TARE_SPOOL2 2508
#define EE_OFF_TARE_SPOOL3 2512
#define EE_OFF_TARE_SPOOL4 2516
#define EE_OFF_STORAGE_AUTO_BASE   2520
#define EE_OFF_STORAGE_AUTO_STRIDE 1
#define EE_OFF_STORAGE_AUTO(i) (EE_OFF_STORAGE_AUTO_BASE + (uint16_t)((i) * EE_OFF_STORAGE_AUTO_STRIDE))
#define EE_OFF_STORAGE_AUTO_DRY_BASE   2523
#define EE_OFF_STORAGE_AUTO_DRY_STRIDE 1
#define EE_OFF_STORAGE_AUTO_DRY(i) (EE_OFF_STORAGE_AUTO_DRY_BASE + (uint16_t)((i) * EE_OFF_STORAGE_AUTO_DRY_STRIDE))
#define EE_OFF_STORAGE_RH_HYST_BASE   2526
#define EE_OFF_STORAGE_RH_HYST_STRIDE 1
#define EE_OFF_STORAGE_RH_HYST(i) (EE_OFF_STORAGE_RH_HYST_BASE + (uint16_t)((i) * EE_OFF_STORAGE_RH_HYST_STRIDE))
#define EE_OFF_STORAGE_DRY_TEMP_MODE_BASE   2529
#define EE_OFF_STORAGE_DRY_TEMP_MODE_STRIDE 1
#define EE_OFF_STORAGE_DRY_TEMP_MODE(i) (EE_OFF_STORAGE_DRY_TEMP_MODE_BASE + (uint16_t)((i) * EE_OFF_STORAGE_DRY_TEMP_MODE_STRIDE))
#define EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP_BASE   2532
#define EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP_STRIDE 1
#define EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP(i) (EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP_BASE + (uint16_t)((i) * EE_OFF_STORAGE_DRY_TEMP_BY_DRY_TEMP_STRIDE))
#define EE_OFF_STORAGE_MIN_HOLD_SEC_BASE   2535
#define EE_OFF_STORAGE_MIN_HOLD_SEC_STRIDE 2
#define EE_OFF_STORAGE_MIN_HOLD_SEC(i) (EE_OFF_STORAGE_MIN_HOLD_SEC_BASE + (uint16_t)((i) * EE_OFF_STORAGE_MIN_HOLD_SEC_STRIDE))
#define EE_OFF_PID_KP_HEATER_BASE   2541
#define EE_OFF_PID_KP_HEATER_STRIDE 4
#define EE_OFF_PID_KP_HEATER(i) (EE_OFF_PID_KP_HEATER_BASE + (uint16_t)((i) * EE_OFF_PID_KP_HEATER_STRIDE))
#define EE_OFF_PID_KI_HEATER_BASE   2553
#define EE_OFF_PID_KI_HEATER_STRIDE 4
#define EE_OFF_PID_KI_HEATER(i) (EE_OFF_PID_KI_HEATER_BASE + (uint16_t)((i) * EE_OFF_PID_KI_HEATER_STRIDE))
#define EE_OFF_PID_KD_HEATER_BASE   2565
#define EE_OFF_PID_KD_HEATER_STRIDE 4
#define EE_OFF_PID_KD_HEATER(i) (EE_OFF_PID_KD_HEATER_BASE + (uint16_t)((i) * EE_OFF_PID_KD_HEATER_STRIDE))
#define EE_OFF_PID_GAIN_HEATER_BASE   2577
#define EE_OFF_PID_GAIN_HEATER_STRIDE 4
#define EE_OFF_PID_GAIN_HEATER(i) (EE_OFF_PID_GAIN_HEATER_BASE + (uint16_t)((i) * EE_OFF_PID_GAIN_HEATER_STRIDE))
#define EE_OFF_PID_KP_CHAMBER_BASE   2589
#define EE_OFF_PID_KP_CHAMBER_STRIDE 4
#define EE_OFF_PID_KP_CHAMBER(i) (EE_OFF_PID_KP_CHAMBER_BASE + (uint16_t)((i) * EE_OFF_PID_KP_CHAMBER_STRIDE))
#define EE_OFF_PID_KI_CHAMBER_BASE   2601
#define EE_OFF_PID_KI_CHAMBER_STRIDE 4
#define EE_OFF_PID_KI_CHAMBER(i) (EE_OFF_PID_KI_CHAMBER_BASE + (uint16_t)((i) * EE_OFF_PID_KI_CHAMBER_STRIDE))
#define EE_OFF_PID_KD_CHAMBER_BASE   2613
#define EE_OFF_PID_KD_CHAMBER_STRIDE 4
#define EE_OFF_PID_KD_CHAMBER(i) (EE_OFF_PID_KD_CHAMBER_BASE + (uint16_t)((i) * EE_OFF_PID_KD_CHAMBER_STRIDE))
#define EE_OFF_PID_GAIN_CHAMBER_BASE   2625
#define EE_OFF_PID_GAIN_CHAMBER_STRIDE 4
#define EE_OFF_PID_GAIN_CHAMBER(i) (EE_OFF_PID_GAIN_CHAMBER_BASE + (uint16_t)((i) * EE_OFF_PID_GAIN_CHAMBER_STRIDE))
#define EE_OFF_HEATER_MAX_TEMP_BASE   2637
#define EE_OFF_HEATER_MAX_TEMP_STRIDE 4
#define EE_OFF_HEATER_MAX_TEMP(i) (EE_OFF_HEATER_MAX_TEMP_BASE + (uint16_t)((i) * EE_OFF_HEATER_MAX_TEMP_STRIDE))
#define EE_OFF_AIR_MAX_TEMP_BASE   2649
#define EE_OFF_AIR_MAX_TEMP_STRIDE 4
#define EE_OFF_AIR_MAX_TEMP(i) (EE_OFF_AIR_MAX_TEMP_BASE + (uint16_t)((i) * EE_OFF_AIR_MAX_TEMP_STRIDE))
#define EE_OFF_DELTA_BASE   2661
#define EE_OFF_DELTA_STRIDE 1
#define EE_OFF_DELTA(i) (EE_OFF_DELTA_BASE + (uint16_t)((i) * EE_OFF_DELTA_STRIDE))
#define EE_OFF_HEATER_DELTA_IS_PERCENT_BASE   2664
#define EE_OFF_HEATER_DELTA_IS_PERCENT_STRIDE 1
#define EE_OFF_HEATER_DELTA_IS_PERCENT(i) (EE_OFF_HEATER_DELTA_IS_PERCENT_BASE + (uint16_t)((i) * EE_OFF_HEATER_DELTA_IS_PERCENT_STRIDE))
#define EE_OFF_VH_MAX_ERR_BASE   2667
#define EE_OFF_VH_MAX_ERR_STRIDE 4
#define EE_OFF_VH_MAX_ERR(i) (EE_OFF_VH_MAX_ERR_BASE + (uint16_t)((i) * EE_OFF_VH_MAX_ERR_STRIDE))
#define EE_OFF_VH_HEATING_GAIN_BASE   2679
#define EE_OFF_VH_HEATING_GAIN_STRIDE 4
#define EE_OFF_VH_HEATING_GAIN(i) (EE_OFF_VH_HEATING_GAIN_BASE + (uint16_t)((i) * EE_OFF_VH_HEATING_GAIN_STRIDE))
#define EE_OFF_VH_CHECK_GAIN_TIME_BASE   2691
#define EE_OFF_VH_CHECK_GAIN_TIME_STRIDE 2
#define EE_OFF_VH_CHECK_GAIN_TIME(i) (EE_OFF_VH_CHECK_GAIN_TIME_BASE + (uint16_t)((i) * EE_OFF_VH_CHECK_GAIN_TIME_STRIDE))
#define EE_OFF_VH_ARM_PWM_MIN_BASE   2697
#define EE_OFF_VH_ARM_PWM_MIN_STRIDE 1
#define EE_OFF_VH_ARM_PWM_MIN(i) (EE_OFF_VH_ARM_PWM_MIN_BASE + (uint16_t)((i) * EE_OFF_VH_ARM_PWM_MIN_STRIDE))
#define EE_OFF_FAN_TEMP_ON_BASE   2700
#define EE_OFF_FAN_TEMP_ON_STRIDE 4
#define EE_OFF_FAN_TEMP_ON(i) (EE_OFF_FAN_TEMP_ON_BASE + (uint16_t)((i) * EE_OFF_FAN_TEMP_ON_STRIDE))
#define EE_OFF_FAN_HYST_BASE   2712
#define EE_OFF_FAN_HYST_STRIDE 4
#define EE_OFF_FAN_HYST(i) (EE_OFF_FAN_HYST_BASE + (uint16_t)((i) * EE_OFF_FAN_HYST_STRIDE))
#define EE_OFF_SERVO_CLOSED_ANGLE_BASE   2724
#define EE_OFF_SERVO_CLOSED_ANGLE_STRIDE 1
#define EE_OFF_SERVO_CLOSED_ANGLE(i) (EE_OFF_SERVO_CLOSED_ANGLE_BASE + (uint16_t)((i) * EE_OFF_SERVO_CLOSED_ANGLE_STRIDE))
#define EE_OFF_SERVO_OPEN_ANGLE_BASE   2727
#define EE_OFF_SERVO_OPEN_ANGLE_STRIDE 1
#define EE_OFF_SERVO_OPEN_ANGLE(i) (EE_OFF_SERVO_OPEN_ANGLE_BASE + (uint16_t)((i) * EE_OFF_SERVO_OPEN_ANGLE_STRIDE))
#define EE_OFF_SERVO_TIME_CLOSED_BASE   2730
#define EE_OFF_SERVO_TIME_CLOSED_STRIDE 2
#define EE_OFF_SERVO_TIME_CLOSED(i) (EE_OFF_SERVO_TIME_CLOSED_BASE + (uint16_t)((i) * EE_OFF_SERVO_TIME_CLOSED_STRIDE))
#define EE_OFF_SERVO_TIME_OPEN_BASE   2736
#define EE_OFF_SERVO_TIME_OPEN_STRIDE 2
#define EE_OFF_SERVO_TIME_OPEN(i) (EE_OFF_SERVO_TIME_OPEN_BASE + (uint16_t)((i) * EE_OFF_SERVO_TIME_OPEN_STRIDE))
#define EE_OFF_SERVO_SMART_MODE_BASE   2742
#define EE_OFF_SERVO_SMART_MODE_STRIDE 1
#define EE_OFF_SERVO_SMART_MODE(i) (EE_OFF_SERVO_SMART_MODE_BASE + (uint16_t)((i) * EE_OFF_SERVO_SMART_MODE_STRIDE))
#define EE_OFF_IGNORE_EXTERNAL_CMD 2745
#define EE_OFF_DRYING_SESSION_COUNT 2746
#define EE_OFF_STORAGE_SESSION_COUNT 2748
#define EE_OFF_PROFILE_SESSION_COUNT 2750
#define EE_OFF_PORT1_MODE 2752
#define EE_OFF_PORT2_MODE 2753
#define EE_OFF_PORT3_MODE 2754
#define EE_OFF_WS_ENABLED 2755
#define EE_OFF_UNITS_COUNT 2756
#define EE_OFF_LANGUAGE 2757

#define EE_TOTAL_SIZE 2758
